### ISSUE TITLE
[BUG] vivillon quest

### ISSUE THREAD

**Issue by Mattwolf2002** [pokeclicker/pokeclicker#2308]
**Info**
 - OS: Windows 8
 - Browser Firefox
 - Version 0.9.5

**Description:**
The quest doesn’t start even after beating the snowbelle city gym

**Steps to Reproduce:**
1.beat snowbelle city gym in kalos
2.check if the quest begin

**Expected Behavior:**
Beginning of the quest

**Additional Information:**
Vanilla game

**Comment by Someonealive-QN** [comment]
The form is not that short im sure of this

**Comment by NiCeDiCe90** [comment]
This bug should be fixed. Can you try to beat the snowbelle gym again?

**Comment by Aegyo** [comment]
Can you share your save file for testing the fix in #2315?

**Comment by Mattwolf2002** [comment]
I tried to beat the gym again and it's still doesn't work
[[v0.9.5] PokeClickerSave_2022-05-30 20 24 59.txt](https://github.com/pokeclicker/pokeclicker/files/8800625/v0.9.5.PokeClickerSave_2022-05-30.20.24.59.txt)
